version: '3.4'

services:
  mysql_server:
    image: mysql:8.0.22
    hostname: 'mysql_server'
    ports:
      - '4406:4406' 
    expose:
      - 4406
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3  
    environment:
      MYSQL_ROOT_PASSWORD: liMin12@*Me
      MYSQL_USER: root
      MYSQL_PASSWORD: liMin12@*Me
      MYSQL_DATABASE: ManagementCompany
  management.api:
    image: ${DOCKER_REGISTRY-}managementapi
    build:
      context: .
      dockerfile: src/Management.Api/Dockerfile
    depends_on:
      - mysql_server
